### ISSUE TITLE
win10 64位 无法运行，请问什么原因？

### ISSUE THREAD

**Issue by s10106** [yinju86/MaaPcrclanbattle#1]
![1](https://github.com/user-attachments/assets/94cd2851-4127-4409-a961-9b9254cc49a9)

**Comment by yinju86** [comment]
不是应该下这个么？[x86_64-v1.0.2.zip](https://github.com/yinju86/MaaPcrclanbattle/releases/download/v1.0.2/MaaPcrclanbattle-win-x86_64-v1.0.2.zip)
