### ISSUE TITLE
UB识别问题

### ISSUE THREAD

**Issue by KarylDAZE** [yinju86/MaaPcrclanbattle#3]
由于使用的是检测TP低于某个值视为在该时间点使用了UB，所以出现了（比如姬塔）在第x秒使用了ub，x+1秒也使用ub，而在刚进x+1秒时姬塔TP很低（此时另一个角色B开了UB），识别为姬塔此时开UB并进行了开关set。
期望表现：角色B开UB时无动作，等姬塔在x+1秒开出UB再进行开关set

具体体现在本次E3轴47秒处：
![image](https://github.com/user-attachments/assets/da3b9bae-f299-432b-b7e0-a0762b7238d2)
![image](https://github.com/user-attachments/assets/0087103a-733e-4bac-a442-34081a0c8234)

**Comment by yinju86** [comment]
新版本添加了延时功能,可以延后数秒再进行检测,以规避该问题,同理bossUB功能也以该方法实现
